
export const interventions = {
    '1xbjZ0RhORdOJeHLuQQtazu2nVc2': {
        gestionnaire: '1WeR1kQNnOaZ6ZkuqF6LkhdjUx42',
        technicien: 'DskAGRFuNsYbFg7fMot3xcyIuil2',
        date: '18/12/2021 16:15',
        duree: 1.5,
        id: '5231',
        titre: 'Changer le chauffe eau',
        agence: 'Foncia',
        nom: 'Dupond',
        prenom: 'Gerard',
        adresse: '15 avenue de la pinede',
        addr: [43.5558793, 7.012570299999999],
        telMobile: "0622027591",
        etat: 'en attente',
        material: ['niveau'],
        taches: [{
            state: 'en attente',
            titre: 'changer le ballon d eau chaude',
            description: 'blablabla ksfhglsfjh',
            image: ["url", "url 2", "..."],
            retourCommentaire: null,
            retourEtat: 1,
            retourPhoto: "rn_image_picker_lib_temp_9d55b68b-440c-41ef-a42c-0659c6c5dcd9.jpg",
            retourRaison: null,

        }]
    },
    '2xbjZ0RhORdOJeHLuQQtazu2nVc2': {
        gestionnaire: '1WeR1kQNnOaZ6ZkuqF6LkhdjUx42',
        technicien: 'GskAGRFuNsYbFg7fMot3xcyIuil2',
        date: '18/12/2021 14:15',
        duree: 1,
        id: '5232',
        titre: 'Changer le radiateur principal',
        agence: 'Foncia',
        nom: 'Bertran',
        prenom: 'Georges',
        adresse: '15 avenue de la pinede',
        addr: [43.5558793, 7.012570299999999],
        telMobile: "0622027591",
        etat: 'non réalisé',
        material: ['niveau'],
        taches: [{
            state: 'réalisé',
            titre: 'nettoyer la chaudière',
            description: 'blablabla kdjshglsf',
            image: ["url", "url 2", "..."],
            retourCommentaire: null,
            retourEtat: 1,
            retourPhoto: "rn_image_picker_lib_temp_9d55b68b-440c-41ef-a42c-0659c6c5dcd9.jpg",
            retourRaison: null,

        },
        {
            state: 'non réalisé',
            titre: 'changer le radiateur du salon',
            description: 'blablabla kdjshglsf',
            image: ["url", "url 2", "..."],
            retourCommentaire: null,
            retourEtat: 1,
            retourPhoto: "rn_image_picker_lib_temp_9d55b68b-440c-41ef-a42c-0659c6c5dcd9.jpg",
            retourRaison: null,

        },
        {
            state: 'en attente',
            titre: 'purger le radiateur',
            description: 'blablabla kdjshglsf',
            image: ["url", "url 2", "..."],
            retourCommentaire: null,
            retourEtat: 1,
            retourPhoto: "rn_image_picker_lib_temp_9d55b68b-440c-41ef-a42c-0659c6c5dcd9.jpg",
            retourRaison: null,

        }]
    },
    '3xbjZ0RhORdOJeHLuQQtazu2nVc2': {
        gestionnaire: '1WeR1kQNnOaZ6ZkuqF6LkhdjUx42',
        technicien: 'BskAGRFuNsYbFg7fMot3xcyIuil2',
        date: '18/12/2021 10:00',
        duree: 4,
        id: '5233',
        titre: 'Changer le disjoncteur',
        agence: 'Foncia',
        nom: 'Wood',
        prenom: 'Hilary',
        adresse: '15 avenue de la pinede',
        addr: [43.5558793, 7.012570299999999],
        telMobile: "0622027591",
        etat: 'réalisé',
        material: ['niveau'],
        taches: [{
            state: 'réalisé',
            titre: 'changer le disjoncteur',
            description: 'blablabla dgfkdsgfsfdjkgbskg',
            image: ["url", "url 2", "..."],
            retourCommentaire: null,
            retourEtat: 1,
            retourPhoto: "rn_image_picker_lib_temp_9d55b68b-440c-41ef-a42c-0659c6c5dcd9.jpg",
            retourRaison: null,

        }]
    },
    '4xbjZ0RhORdOJeHLuQQtazu2nVc2': {
        gestionnaire: '1WeR1kQNnOaZ6ZkuqF6LkhdjUx42',
        technicien: 'DskAGRFuNsYbFg7fMot3xcyIuil2',
        date: '18/12/2021 14:30',
        duree: 1,
        id: '5234',
        titre: 'Changer la porte d entree',
        agence: 'Foncia',
        nom: 'Haim',
        prenom: 'Chloe',
        adresse: '15 avenue de la pinede',
        addr: [43.5558793, 7.012570299999999],
        telMobile: "0622027591",
        etat: 'en cours',
        material: ['niveau'],
        taches: [{
            state: 'en cours',
            titre: 'changer la porte d entree',
            description: 'blablabla blabla',
            image: ["url", "url 2", "..."],
            retourCommentaire: null,
            retourEtat: 1,
            retourPhoto: "rn_image_picker_lib_temp_9d55b68b-440c-41ef-a42c-0659c6c5dcd9.jpg",
            retourRaison: null,

        }]
    },
    '5xbjZ0RhORdOJeHLuQQtazu2nVc2': {
        gestionnaire: '1WeR1kQNnOaZ6ZkuqF6LkhdjUx42',
        technicien: 'DskAGRFuNsYbFg7fMot3xcyIuil2',
        date: '18/12/2021 9:30',
        duree: 3.5,
        id: '5224',
        titre: 'Changer la porte d entrée',
        agence: 'Foncia',
        nom: 'Haim',
        prenom: 'Chloe',
        adresse: '15 avenue de la pinede',
        addr: [43.5558793, 7.012570299999999],
        telMobile: "0622027591",
        etat: 'annulé',
        material: ['niveau'],
        taches: [{
            state: 'non réalisé',
            titre: 'changer la porte d entree',
            description: 'blablabla blabla',
            image: ["url", "url 2", "..."],
            retourCommentaire: null,
            retourEtat: 1,
            retourPhoto: "rn_image_picker_lib_temp_9d55b68b-440c-41ef-a42c-0659c6c5dcd9.jpg",
            retourRaison: null,

        }]
    },
    '6xbjZ0RhORdOJeHLuQQtazu2nVc2': {
        gestionnaire: '1WeR1kQNnOaZ6ZkuqF6LkhdjUx42',
        technicien: 'CskAGRFuNsYbFg7fMot3xcyIuil2',
        date: '18/12/2021 8:00',
        duree: 1,
        id: '5214',
        titre: 'Changer la porte d entrée',
        agence: 'Foncia',
        nom: 'Haim',
        prenom: 'Chloe',
        adresse: '15 avenue de la pinede',
        addr: [43.5558793, 7.012570299999999],
        telMobile: "0622027591",
        etat: 'payé',
        material: ['niveau'],
        taches: [{
            state: 'réalisé',
            titre: 'changer la porte d entree',
            description: 'blablabla blabla',
            image: ["url", "url 2", "..."],
            retourCommentaire: null,
            retourEtat: 1,
            retourPhoto: "rn_image_picker_lib_temp_9d55b68b-440c-41ef-a42c-0659c6c5dcd9.jpg",
            retourRaison: null,

        }]
    }
}